Repository boostcampwm-2022/web29-Buddha, pull requests merged in 2022-11, with the labels that each got.

#8 이슈 #1 / [Feature] : 페이지 라우팅
  package-lock.json
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/Layout.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#9 Nest js Config 설정 및 Naver OAuth 테스트 코드
  .eslintrc.json
  package-lock.json
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.controller.spec.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/auth.entity.ts
  packages/server/src/main.ts
Labels: 💻 백엔드

#10 TypeORM 기본세팅
  package-lock.json
  package.json
  packages/server/src/app.module.ts
Labels: 💻 백엔드, ✨ FEAT

#11 Week2 - Day01
  .eslintrc.json
  package-lock.json
  package.json
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.controller.spec.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/auth.entity.ts
  packages/server/src/main.ts
Labels: 💻 백엔드

#12 로그인 페이지
  packages/client/src/App.tsx
  packages/client/src/pages/Signin/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#13 회원가입 페이지 기본 제작
  package-lock.json
  packages/client/src/App.tsx
  packages/client/src/constants.ts
  packages/client/src/pages/Signup/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#14 Week2 - Day01
  package-lock.json
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/Layout.tsx
  packages/client/src/constants.ts
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#15 Week2 - Day01
  package-lock.json
  package.json
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/Layout.tsx
  packages/client/src/constants.ts
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.controller.spec.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/auth.entity.ts
  packages/server/src/main.ts
Labels: 🎨 프론트엔드, 💻 백엔드, ✨ FEAT

#16 Emotion 추가 및 Theme 적용
  package-lock.json
  packages/client/package.json
  packages/client/src/Layout.tsx
  packages/client/src/index.css
  packages/client/src/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#17 테스트 스크립트 수정
  packages/client/package.json
Labels: 🎨 프론트엔드, 🐞 BUG

#18 레이아웃 스타일링
  packages/client/src/Layout.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#20 Typeorm entity 설정
  packages/server/src/app.module.ts
  packages/server/src/cafe/cafe.controller.spec.ts
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.module.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/create-cafe.dto.ts
  packages/server/src/cafe/dto/update-cafe.dto.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/cafeMenu.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/cafe/entities/menuOption.entity.ts
  packages/server/src/cafe/entities/option.entity.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/update-order.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.controller.spec.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.module.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
  packages/server/src/user/dto/create-user.dto.ts
  packages/server/src/user/dto/update-user.dto.ts
  packages/server/src/user/entities/token.entity.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/user.controller.spec.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#21 절대 경로 alias 버그 수정
  package-lock.json
  packages/client/craco.config.ts
  packages/client/package.json
Labels: 🎨 프론트엔드, 🐞 BUG

#22 Nest js Config 설정
  package-lock.json
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/main.ts
Labels: 💻 백엔드, ✨ FEAT

#24 cross-env 추가
  package-lock.json
  packages/server/package.json
Labels: 💻 백엔드, 🐞 BUG

#23 로그인 페이지 (요소 수정, 테스팅, 스타일링)
  packages/client/src/pages/.gitkeep
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signin/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#25 회원가입 페이지 테스트 코드 작성 및 스타일 적용
  packages/client/public/index.html
  packages/client/src/constants.ts
  packages/client/src/index.css
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/Signup/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#27 user 모듈 기본 틀 설정
  package-lock.json
  packages/server/package.json
  packages/server/src/user/dto/create-user.dto.ts
  packages/server/src/user/dto/signup.dto.ts
  packages/server/src/user/dto/update-user.dto.ts
  packages/server/src/user/enum/userType.enum.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#32 카페 별 메뉴 조회, router 설정
  packages/server/config/route.ts
  packages/server/src/app.controller.ts
  packages/server/src/app.module.ts
  packages/server/src/app.service.ts
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.module.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/CafeMenuRes.dto.ts
  packages/server/src/cafe/dto/MenuRes.dto.ts
  packages/server/src/cafe/dto/create-cafe.dto.ts
  packages/server/src/cafe/dto/update-cafe.dto.ts
Labels: 💻 백엔드, ✨ FEAT

#36 유저 로그인 성공 케이스
  package-lock.json
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/interfaces/jwtPayload.ts
  packages/server/src/user/dto/naver-singIn.dto.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#38 회원가입 api 구현
  packages/server/src/auth/auth.service.ts
  packages/server/src/user/dto/signup.dto.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#34 [BE] 메뉴에 대한 상세정보, 옵션 조회
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/MenuDetailRes.dto.ts
  packages/server/src/cafe/dto/OptionRes.dto.ts
Labels: 💻 백엔드, ✨ FEAT

#39 CSS 우선순위 변경
  packages/client/src/pages/Signin/styled.ts
Labels: 🎨 프론트엔드

#41 Week2 - Day03
  package-lock.json
  packages/server/.gitignore
  packages/server/config/route.ts
  packages/server/package.json
  packages/server/src/app.controller.ts
  packages/server/src/app.module.ts
  packages/server/src/app.service.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/interfaces/jwtPayload.ts
  packages/server/src/cafe/cafe.controller.spec.ts
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.module.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/CafeMenuRes.dto.ts
  packages/server/src/cafe/dto/MenuDetailRes.dto.ts
  packages/server/src/cafe/dto/MenuRes.dto.ts
  packages/server/src/cafe/dto/OptionRes.dto.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/cafeMenu.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/cafe/entities/menuOption.entity.ts
  packages/server/src/cafe/entities/option.entity.ts
  packages/server/src/main.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/update-order.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.controller.spec.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.module.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
  packages/server/src/user/dto/naver-singIn.dto.ts
  packages/server/src/user/dto/signup.dto.ts
  packages/server/src/user/dto/update-user.dto.ts
  packages/server/src/user/entities/token.entity.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/enum/userType.enum.ts
  packages/server/src/user/user.controller.spec.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드

#40 회원가입 페이지 스타일 적용 및 테스트 추가 적용
  package-lock.json
  packages/client/craco.config.ts
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/Router.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/Signup/styled.ts
  packages/client/src/pages/customer/OrderList/index.tsx
  packages/client/src/types/Signup.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#42 Week2 - Day3
  .github/pull_request_template.md
  package-lock.json
  packages/client/craco.config.ts
  packages/client/package.json
  packages/client/public/index.html
  packages/client/src/App.tsx
  packages/client/src/Layout.tsx
  packages/client/src/Router.tsx
  packages/client/src/constants.ts
  packages/client/src/index.css
  packages/client/src/index.tsx
  packages/client/src/pages/.gitkeep
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signin/styled.ts
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/Signup/styled.ts
  packages/client/src/pages/customer/OrderList/index.tsx
  packages/client/src/types/Signup.ts
  packages/client/tsconfig.json
Labels: 🎨 프론트엔드, ✨ FEAT

#44 로그인 페이지 요청 및 응답 로직
  packages/client/src/index.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/server/src/main.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#43 API스펙에 맞게 코드 수정
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/types/Signup.ts
Labels: 🎨 프론트엔드, 🔨 REFACTOR

#46 회원가입 버그 수정
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/server/src/main.ts
Labels: 🎨 프론트엔드, 💻 백엔드, 🐞 BUG

#47 서버 배포를 위한 도커파일 작성
  .dockerignore
  Dockerfile
  docker-compose.yml
  packages/server/package.json
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#50 nginx를 이용한 리액트 빌드파일 배포
  .dockerignore
  Dockerfile
  docker-compose.yml
  packages/client/src/index.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/types/Signup.ts
  packages/nginx/configs/conf.d/default.conf
  packages/nginx/configs/fastcgi_params
  packages/nginx/configs/mime.types
  packages/nginx/configs/modules
  packages/nginx/configs/nginx.conf
  packages/nginx/configs/scgi_params
  packages/nginx/configs/uwsgi_params
  packages/nginx/dockerfile
  packages/server/package.json
  packages/server/src/main.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#51 Week2 - Day3 BE
  docker-compose.yml
  packages/nginx/configs/conf.d/default.conf
  packages/nginx/configs/fastcgi_params
  packages/nginx/configs/mime.types
  packages/nginx/configs/modules
  packages/nginx/configs/nginx.conf
  packages/nginx/configs/scgi_params
  packages/nginx/configs/uwsgi_params
  packages/nginx/dockerfile
Labels: 💻 백엔드

#54 리모트 서버 cors 에러 이슈, docker-compose 관련 이슈 해결
  .gitignore
  packages/server/src/auth/auth.service.ts
  packages/server/src/main.ts
Labels: 🐞 BUG

#56 docker 실행환경에 따라 환경변수 설정
  docker-compose.yml
Labels: 💻 백엔드, 🔨 REFACTOR

#61 FE dev ci 깃헙 액션 등록
  .github/workflows/fe-dev-ci.yml
  .gitignore
  packages/server/src/auth/auth.service.ts
  packages/server/src/main.ts
Labels: 💻 백엔드, ✨ FEAT

#62 로그인 페이지 #57, #58 버그 수정
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/types/.gitkeep
  packages/client/src/types/Signin.ts
Labels: 🎨 프론트엔드, 🐞 BUG

#63 회원가입 페이지 코드리뷰 피드백 작업
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/types/Signup.ts
Labels: 🎨 프론트엔드, 🔨 REFACTOR

#64 FE dev ci 깃헙 액션 등록
  .github/workflows/fe-dev-cd.yml
  .github/workflows/fe-dev-ci.yml
  packages/client/test.txt
Labels: 💻 백엔드, ✨ FEAT

#65 FE Dev CI/CD 등록
  .github/workflows/fe-dev-cd.yml
  .github/workflows/fe-dev-ci.yml
  docker-compose.yml
  packages/client/test.txt
  packages/server/src/auth/auth.service.ts
Labels: 💻 백엔드, ✨ FEAT

#68 버그 수정 및 회원가입 페이지 리팩토링
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/types/.gitkeep
  packages/client/src/types/Signin.ts
  packages/client/src/types/Signup.ts
Labels: 🎨 프론트엔드, 🐞 BUG, 🔨 REFACTOR

#77 로그인 페이지 테스트 작성
  packages/client/src/mocks/handlers/auth.ts
  packages/client/src/mocks/handlers/index.ts
  packages/client/src/mocks/server.ts
  packages/client/src/pages/Signin/__snapshots__/index.spec.tsx.snap
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signin/styled.ts
Labels: 🎨 프론트엔드

#78 user auth 모듈 관심사 분리, passport, guard 적용
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/types/.gitkeep
  packages/client/src/types/Signin.ts
  packages/client/src/types/Signup.ts
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/dto/naver-singIn.dto.ts
  packages/server/src/auth/dto/signup.dto.ts
  packages/server/src/auth/guard/jwt.guard.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/main.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT, 🔨 REFACTOR

#79 메뉴 상세정보 응답 DTO 수정
  packages/server/src/cafe/dto/MenuDetailRes.dto.ts
  packages/server/src/order/order.controller.ts
Labels: 💻 백엔드, 🐞 BUG

#82 user auth 모듈 리팩토링, auth service 테스트 코드 작성
  packages/server/package.json
  packages/server/src/app.controller.spec.ts
  packages/server/src/auth/auth.controller.spec.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/entities/token.entity.ts
  packages/server/src/auth/naverOAuth.service.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/cafe/cafe.controller.spec.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/order/order.controller.spec.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/user/user.controller.spec.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#80 Footer 및 메뉴 리스트 페이지 기본 구현
  packages/client/src/Router.tsx
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/Footer/styled.ts
  packages/client/src/components/MenuItem/index.tsx
  packages/client/src/components/MenuItem/styled.ts
  packages/client/src/components/SnackBar/index.tsx
  packages/client/src/components/SnackBar/styled.ts
  packages/client/src/pages/MenuList/index.spec.tsx
  packages/client/src/pages/MenuList/index.tsx
  packages/client/src/pages/MenuList/styled.ts
  packages/client/src/types/MenuList.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#84 Week3 - Day1
  packages/server/package.json
  packages/server/src/app.controller.spec.ts
  packages/server/src/auth/auth.controller.spec.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/dto/naver-singIn.dto.ts
  packages/server/src/auth/dto/signup.dto.ts
  packages/server/src/auth/entities/token.entity.ts
  packages/server/src/auth/guard/jwt.guard.ts
  packages/server/src/auth/naverOAuth.service.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/cafe/cafe.controller.spec.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/dto/MenuDetailRes.dto.ts
  packages/server/src/main.ts
  packages/server/src/order/order.controller.spec.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/user/user.controller.spec.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.module.ts
  packages/server/src/user/user.service.spec.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드

#83 메뉴 상세 페이지
  packages/client/src/Router.tsx
  packages/client/src/components/OptionSelector/index.tsx
  packages/client/src/components/OptionSelector/styled.ts
  packages/client/src/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/components/SizeSelector/index.test.tsx
  packages/client/src/components/SizeSelector/index.tsx
  packages/client/src/components/SizeSelector/styled.ts
  packages/client/src/components/TypeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/components/TypeSelector/index.test.tsx
  packages/client/src/components/TypeSelector/index.tsx
  packages/client/src/components/TypeSelector/styled.ts
  packages/client/src/constants.ts
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuDetail/styled.ts
  packages/client/src/types/MenuDetail.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#85 테스트 코드 리팩토링
  packages/client/src/mocks/handlers/auth.ts
  packages/client/src/mocks/handlers/index.ts
  packages/client/src/mocks/handlers/menu.ts
  packages/client/src/pages/MenuList/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
Labels: 🎨 프론트엔드, 🔨 REFACTOR

#86 주문 상세 페이지 테스트 및 유틸 추가
  packages/client/src/components/.gitkeep
  packages/client/src/components/OptionSelector/index.test.tsx
  packages/client/src/components/OptionSelector/index.tsx
  packages/client/src/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/components/SizeSelector/index.tsx
  packages/client/src/mocks/handlers/menu.ts
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/utils/.gitkeep
  packages/client/src/utils/index.test.ts
  packages/client/src/utils/index.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#87 메뉴 리스트 페이지 스타일 적용 및 버튼 컴포넌트 분리
  packages/client/src/components/Button/index.tsx
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/Footer/styled.ts
  packages/client/src/components/MenuItem/index.tsx
  packages/client/src/components/MenuItem/styled.ts
  packages/client/src/components/SnackBar/styled.ts
  packages/client/src/pages/MenuList/styled.ts
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/Signup/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#88 헤더 컴포넌트 추가
  packages/client/src/components/Header/__snapshots__/index.test.tsx.snap
  packages/client/src/components/Header/index.test.tsx
  packages/client/src/components/Header/index.tsx
  packages/client/src/components/Header/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#89 아이콘 추가 작업 및 메뉴 리스트 페이지 수정 작업
  packages/client/craco.config.ts
  packages/client/src/assets/icons/cart.svg
  packages/client/src/assets/icons/change.svg
  packages/client/src/assets/icons/down_arrow.svg
  packages/client/src/assets/icons/edit_nickname.svg
  packages/client/src/assets/icons/home.svg
  packages/client/src/assets/icons/left_arrow.svg
  packages/client/src/assets/icons/logout.svg
  packages/client/src/assets/icons/mypage.svg
  packages/client/src/assets/icons/order.svg
  packages/client/src/assets/icons/receipt.svg
  packages/client/src/assets/icons/signout.svg
  packages/client/src/assets/icons/size.svg
  packages/client/src/assets/icons/x_icon.svg
  packages/client/src/components/Footer/NavigateItem.tsx
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/Footer/styled.ts
  packages/client/src/components/SnackBar/index.tsx
  packages/client/src/components/SnackBar/styled.ts
  packages/client/src/pages/MenuList/index.tsx
  packages/client/tsconfig.json
Labels: 🎨 프론트엔드, ✨ FEAT

#91 menu entity, dto에 category column 추가
  packages/server/src/cafe/dto/MenuRes.dto.ts
  packages/server/src/cafe/entities/menu.entity.ts
Labels: 💻 백엔드, ✨ FEAT

#93 장바구니 페이지 레이아웃 작업
  packages/client/src/Router.tsx
  packages/client/src/components/Button/index.tsx
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/CartFooter/index.tsx
  packages/client/src/components/CartFooter/styled.ts
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/Cart/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#94 상세 페이지 음료 수량, 총 가격, localStorage 저장 추가
  packages/client/src/assets/icons/minus.svg
  packages/client/src/assets/icons/plus.svg
  packages/client/src/components/QuantitySelector/index.tsx
  packages/client/src/components/QuantitySelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuDetail/styled.ts
  packages/client/src/pages/customer/OrderList/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#95 Week3 - 주문 내역 조회, 주문 생성 api 1차 구현
  packages/server/src/app.module.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/cafe/dto/MenuRes.dto.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/orderMenu.dto.ts
  packages/server/src/order/dto/orderRes.dto.ts
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/enum/orderStatus.enum.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.module.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, ✨ FEAT, 🔨 REFACTOR

#96 모든 entity createdAt, updatedAt 추가 및 자잘한 entity 수정
  packages/server/src/auth/entities/token.entity.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/cafeMenu.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/cafe/entities/menuOption.entity.ts
  packages/server/src/cafe/entities/option.entity.ts
  packages/server/src/cafe/enum/menuType.enum.ts
  packages/server/src/common/entities/common.entity.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/enum/userType.enum.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#97 주문 요청 관련 size type 수정
  packages/server/src/cafe/enum/menuSize.enum.ts
  packages/server/src/cafe/enum/menuType.enum.ts
  packages/server/src/order/dto/orderMenu.dto.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#99 주문 내역 조회 api 응답에 날짜 추가, option 객체화
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#98 카페 entity 수정, 메뉴(+상세정보) 조회 테스트 코드 작성
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/CafeMenuRes.dto.ts
Labels: 💻 백엔드, ✨ FEAT

#100 주문 내역 페이지 날짜별 내역 분리
  packages/client/src/components/HistoryItem/index.tsx
  packages/client/src/components/HistoryItem/styled.ts
  packages/client/src/containers/.gitkeep
  packages/client/src/containers/HistoryByDate/index.tsx
  packages/client/src/containers/HistoryByDate/styled.ts
  packages/client/src/containers/HistoryContainer/index.tsx
  packages/client/src/containers/HistoryContainer/styled.ts
  packages/client/src/mocks/data/order.ts
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/OrderList/index.tsx
  packages/client/src/pages/customer/OrderList/styled.ts
  packages/client/src/types/OrderList.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#102 localStorage 장바구니 관련 작업 및 장바구니 페이지 구현
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/CartFooter/index.tsx
  packages/client/src/components/CartFooter/styled.ts
  packages/client/src/components/CartItem/index.tsx
  packages/client/src/components/CartItem/styled.ts
  packages/client/src/components/EmptyCart/index.tsx
  packages/client/src/components/EmptyCart/styled.ts
  packages/client/src/components/SnackBar/index.tsx
  packages/client/src/constants.ts
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/Cart/styled.ts
  packages/client/src/types/Cart.ts
  packages/client/src/utils/localStorage.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#103 주문 요청 api 옵션 검사 로직, 총 금액 계산 로직 추가
  packages/server/src/order/order.module.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#105 menuOptionDict의 price 필드를 menuPrice로 수정
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#104 음료 가격 저장 수정
  packages/client/src/components/OptionSelector/index.tsx
  packages/client/src/components/OptionSelector/styled.ts
  packages/client/src/components/SizeSelector/index.tsx
  packages/client/src/components/SizeSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuDetail/styled.ts
Labels: 🎨 프론트엔드, 🐞 BUG

#107 Week Day4 BE
  packages/server/src/auth/entities/token.entity.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/CafeMenuRes.dto.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/cafeMenu.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/cafe/entities/menuOption.entity.ts
  packages/server/src/cafe/entities/option.entity.ts
  packages/server/src/cafe/enum/menuSize.enum.ts
  packages/server/src/cafe/enum/menuType.enum.ts
  packages/server/src/common/entities/common.entity.ts
  packages/server/src/order/dto/orderMenu.dto.ts
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.module.ts
  packages/server/src/order/order.service.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/enum/userType.enum.ts
Labels: 💻 백엔드

#106 뒤로가기 버튼, 수량 선택 컴포넌트 추가 및 수정
  packages/client/src/components/LeftArrow/index.tsx
  packages/client/src/components/LeftArrow/styled.ts
  packages/client/src/components/QuantitySelector/index.tsx
  packages/client/src/components/QuantitySelector/styled.ts
  packages/client/src/pages/customer/Cart/components/CartItem/index.tsx
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/Cart/styled.ts
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuDetail/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#110 Hotfix/be/fe ci cd
  .github/workflows/fe-dev-cd.yml
  .github/workflows/fe-dev-ci.yml
Labels: 🐞 BUG

#114 fix: [BE] 로그인 오류 수정
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/naverOAuth.service.ts
Labels: 💻 백엔드, 🐞 BUG

#111 FE 테스트 오류 수정
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/QuantitySelector/index.tsx
  packages/client/src/components/QuantitySelector/styled.ts
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
Labels: 🎨 프론트엔드, 🐞 BUG

#113 주문하기 이후 동작 구현
  packages/client/src/pages/customer/Cart/components/CartFooter/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#116 주문 상태 조회 api 구현
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, ✨ FEAT

#123 validate and guard
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/public.decorator.ts
  packages/server/src/auth/decorators/roles.decorator.ts
  packages/server/src/auth/dto/signup.dto.ts
  packages/server/src/auth/guard/jwt.guard.ts
  packages/server/src/auth/guard/role.guard.ts
  packages/server/src/auth/interfaces/jwtPayload.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/enum/userRole.enum.ts
Labels: 💻 백엔드, ✨ FEAT, 🔨 REFACTOR

#124 업주 주문 내역 조회 및 상태 변경
  packages/server/src/order/dto/updateOrderReq.dto.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, ✨ FEAT

#125 Week4 Day1
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/decorators/public.decorator.ts
  packages/server/src/auth/decorators/roles.decorator.ts
  packages/server/src/auth/dto/signup.dto.ts
  packages/server/src/auth/guard/jwt.guard.ts
  packages/server/src/auth/guard/role.guard.ts
  packages/server/src/auth/interfaces/jwtPayload.ts
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/updateOrderReq.dto.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.service.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/user/enum/userRole.enum.ts
Labels: ✨ FEAT, 🔨 REFACTOR

#126 주문하기 API 예외처리 로직 잘못된 것 수정
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🐞 BUG

#127 feat: [FE] 고객 주문 내역 조회 컴포넌트 -> 공통 컴포넌트
  packages/client/src/components/HistoryByDate/index.tsx
  packages/client/src/components/HistoryByDate/styled.ts
  packages/client/src/components/HistoryDetail/index.tsx
  packages/client/src/components/HistoryDetail/styled.ts
  packages/client/src/components/HistoryItem/index.tsx
  packages/client/src/components/HistoryItem/styled.ts
  packages/client/src/pages/customer/OrderList/components/HistoryContainer/index.tsx
  packages/client/src/pages/customer/OrderList/components/HistoryContainer/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#130 마이페이지, 주문 현황 페이지 제작 및 메뉴 리스트 페이지 리뉴얼
  packages/client/src/Router.tsx
  packages/client/src/assets/icons/logout.svg
  packages/client/src/assets/icons/signout.svg
  packages/client/src/assets/icons/withdrawal.svg
  packages/client/src/constants.ts
  packages/client/src/pages/MyPage/index.tsx
  packages/client/src/pages/MyPage/styled.ts
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/MenuList/index.tsx
  packages/client/src/pages/customer/MenuList/styled.ts
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/pages/customer/OrderStatus/styled.ts
  packages/client/src/types/MenuList.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#132 고객 주문 내역 페이지, 업주 주문 요청/수락 내역 페이지
  packages/client/src/Router.tsx
  packages/client/src/components/HistoryByDate/index.tsx
  packages/client/src/components/HistoryDetail/index.tsx
  packages/client/src/components/HistoryItem/index.tsx
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDateList/styled.ts
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderDetailList/styled.ts
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/components/OrderList/styled.ts
  packages/client/src/hooks/.gitkeep
  packages/client/src/hooks/useFetch.tsx
  packages/client/src/hooks/useOrderDates.tsx
  packages/client/src/mocks/handlers/auth.ts
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Home/styled.ts
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/Cart/components/CartFooter/index.tsx
  packages/client/src/pages/customer/Cart/components/CartItem/index.tsx
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/MenuDetail/components/OptionSelector/index.tsx
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/index.test.tsx
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/index.tsx
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/TypeSelector/index.test.tsx
  packages/client/src/pages/customer/MenuDetail/components/TypeSelector/index.tsx
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuList/components/MenuItem/index.tsx
  packages/client/src/pages/customer/MenuList/index.tsx
  packages/client/src/pages/customer/OrderList/components/HistoryContainer/index.tsx
  packages/client/src/pages/customer/OrderList/components/HistoryContainer/styled.ts
  packages/client/src/pages/customer/OrderList/index.tsx
  packages/client/src/pages/manager/AcceptList/index.tsx
  packages/client/src/pages/manager/AcceptList/styled.ts
  packages/client/src/types/Cart.ts
  packages/client/src/types/MenuDetail.ts
  packages/client/src/types/MenuList.ts
  packages/client/src/types/OrderList.ts
  packages/client/src/types/Signin.ts
  packages/client/src/types/Signup.ts
  packages/client/src/types/index.ts
  packages/client/src/utils/localStorage.ts
  packages/client/src/utils/store.ts
Labels: 🎨 프론트엔드, ✨ FEAT, 🔨 REFACTOR

#135 업주 주문 요청/수락 페이지 (상태 변경 버튼 추가)
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderDetailList/styled.ts
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/hooks/useFetch.tsx
  packages/client/src/types/index.ts
  packages/client/src/utils/store.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#136 주문 내역 응답 객체 date 형식 변경
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/utils/dateTime.util.spec.ts
  packages/server/src/utils/dateTime.util.ts
Labels: 💻 백엔드, ✨ FEAT
