Repository boostcampwm-2022/web29-Buddha, pull requests merged in 2022-12, with the labels that each got.

#137 코드 리팩토링 및 테스트 코드 작업
  packages/client/src/components/Footer/index.spec.tsx
  packages/client/src/mocks/data/menu.ts
  packages/client/src/mocks/handlers/index.ts
  packages/client/src/mocks/handlers/order.ts
  packages/client/src/pages/MyPage/index.tsx
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/pages/customer/Cart/index.tsx
  packages/client/src/pages/customer/MenuDetail/index.tsx
  packages/client/src/pages/customer/MenuList/components/SnackBar/index.tsx
  packages/client/src/pages/customer/MenuList/index.spec.tsx
  packages/client/src/pages/customer/MenuList/index.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/utils/testSetup.tsx
Labels: 🎨 프론트엔드, ✨ FEAT, 🔨 REFACTOR

#140 order service의 create 함수 테스트 코드 작성
  packages/server/src/cafe/mock/menu.entity.mock.ts
  packages/server/src/cafe/mock/menuOptionRelation.mock.ts
  packages/server/src/cafe/mock/mockDataGenerator.ts
  packages/server/src/cafe/mock/option.entity.mock.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, ✨ FEAT

#143 fix: [hotfix] ci cd 수정
  .github/workflows/be-dev-cd.yml
  .github/workflows/fe-dev-ci.yml
Labels: 🐞 BUG

#144 릴리즈를 위한 Type 관련 작업
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/constants.ts
  packages/client/src/hooks/useOrderDates.tsx
  packages/client/src/mocks/handlers/auth.ts
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/types/index.ts
Labels: 🎨 프론트엔드, 🔨 REFACTOR

#145 singUp 시 쿠키에 Access Token 주입해서 응답하도록 수정
  packages/server/src/auth/auth.controller.ts
Labels: 🐞 BUG

#146 fix: [hotfix] 가격 계산 로직에 size 추가
  packages/server/src/cafe/enum/menuSize.enum.ts
  packages/server/src/cafe/mock/mockDataGenerator.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🐞 BUG

#149 BE Logger 추가
  packages/server/src/app.module.ts
  packages/server/src/main.ts
  packages/server/src/middleware/exception.filter.ts
  packages/server/src/middleware/logger.http.ts
Labels: 💻 백엔드, ✨ FEAT

#155 [hotfix] : nest js 실행안되던 버그 수정
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/order.controller.ts
  packages/server/src/order/order.service.ts
Labels: 💻 백엔드, 🐞 BUG

#157 공통으로 사용할 비동기 요청 관련 Custom Hooks 제작
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/constants.ts
  packages/client/src/hooks/useCustomQuery.tsx
  packages/client/src/hooks/useMenuListData.tsx
  packages/client/src/pages/customer/MenuList/index.tsx
  packages/client/src/utils/fetch.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#160 주문 현황 polling 구현 및 권한별 라우팅 분리
  packages/client/src/App.tsx
  packages/client/src/Router.tsx
  packages/client/src/UserRoleProvider.tsx
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/Footer/styled.ts
  packages/client/src/constants.ts
  packages/client/src/hooks/useCustomQuery.tsx
  packages/client/src/hooks/useOrderStatus.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/types/index.ts
  packages/client/src/utils/store.ts
  packages/server/src/auth/auth.controller.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#163 주문 api 캐싱 추가
  packages/server/config/route.ts
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/order/dto/oldRequestedOrdersDto.ts
  packages/server/src/order/dto/requested-order.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/order.service.ts
  packages/server/src/order/order.v1.controller.ts
  packages/server/src/order/order.v1.module.ts
  packages/server/src/order/order.v2.controller.ts
  packages/server/src/order/order.v2.module.ts
  packages/server/src/redisCache/redisCache.module.ts
  packages/server/src/redisCache/redisCache.service.ts
Labels: 💻 백엔드, ✨ FEAT, 🔨 REFACTOR

#168 Order 응답 객체 수정
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/utils/dateTime.util.spec.ts
Labels: 💻 백엔드, 🐞 BUG

#166 주문 내역 Polling, 수락/거절/제조완료 로직
  packages/client/src/Router.tsx
  packages/client/src/UserRoleProvider.tsx
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/constants.ts
  packages/client/src/hooks/useCustomQuery.tsx
  packages/client/src/hooks/useFetchOrderList.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/manager/AcceptList/index.tsx
  packages/client/src/stores/index.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#170 유저 권한별 라우팅 설정으로 인한 테스트 코드 리팩토링
  packages/client/src/components/Footer/index.spec.tsx
  packages/client/src/mocks/data/order.ts
  packages/client/src/mocks/handlers/auth.ts
  packages/client/src/mocks/handlers/order.ts
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/customer/Cart/components/CartFooter/index.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
  packages/client/src/pages/customer/MenuList/index.spec.tsx
  packages/client/src/utils/testSetup.tsx
Labels: 🎨 프론트엔드, ✨ FEAT, 🔨 REFACTOR

#171 주문 내역 옵션 정보 추가
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderDetailList/styled.ts
  packages/client/src/types/index.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#169 BE - Week5 Day4
  packages/server/jest-e2e.json
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/cafe/entities/cafe.entity.ts
  packages/server/src/cafe/entities/menu.entity.ts
  packages/server/src/config/route.ts
  packages/server/src/main.ts
  packages/server/src/middleware/exception.filter.ts
  packages/server/src/middleware/logger.http.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/oldRequestedOrdersDto.ts
  packages/server/src/order/dto/orderMenu.dto.ts
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/dto/requested-order.dto.ts
  packages/server/src/order/entities/order.entity.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.entity.spec.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
  packages/server/src/order/order.v1.controller.ts
  packages/server/src/order/order.v1.module.ts
  packages/server/src/order/order.v2.controller.ts
  packages/server/src/order/order.v2.module.ts
  packages/server/src/redisCache/redisCache.module.ts
  packages/server/src/redisCache/redisCache.service.ts
  packages/server/src/setEnvVar.ts
  packages/server/src/setNestApp.ts
  packages/server/src/user/entities/user.entity.ts
  packages/server/src/utils/dateTime.util.spec.ts
  packages/server/src/utils/getMySQLTestTypeOrmModule.ts
  packages/server/test/app.e2e-spec.ts
  packages/server/test/e2e/order/order.e2e.spec.ts
  packages/server/test/integration/order/order.int.spec.ts
  packages/server/test/jest-e2e.json
  packages/server/test/mock/create-cafe.json
  packages/server/test/mock/create-order.json
  packages/server/test/mock/menu-option-dict.json
  packages/server/test/mock/menu-option.json
Labels: 💻 백엔드

#173 미흡한 테스트 코드 작성
  packages/client/src/mocks/data/cart.ts
  packages/client/src/mocks/data/order.ts
  packages/client/src/mocks/handlers/order.ts
  packages/client/src/pages/MyPage/index.spec.tsx
  packages/client/src/pages/customer/Cart/components/CartItem/index.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
  packages/client/src/pages/customer/MenuList/components/MenuItem/index.tsx
  packages/client/src/pages/customer/OrderStatus/index.spec.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
Labels: 🎨 프론트엔드, ✨ FEAT

#179 주문 내역 페이지 버그 수정
  packages/client/src/components/Footer/index.spec.tsx
  packages/client/src/components/Header/__snapshots__/index.test.tsx.snap
  packages/client/src/components/Header/index.test.tsx
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/hooks/useOrderDates.tsx
  packages/client/src/pages/Home/index.test.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/utils/index.ts
Labels: 🎨 프론트엔드, 🐞 BUG

#182 업주 주문 목록 페이지 초기 설정 변경
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDateList/styled.ts
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/pages/Home/index.tsx
Labels: 🎨 프론트엔드

#184 Week6 백엔드 잔버그들 수정
  packages/server/src/app.module.ts
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/dto/CafeRes.dto.ts
  packages/server/src/order/order.service.ts
  packages/server/src/user/user.controller.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, 🐞 BUG, 🔨 REFACTOR

#183 불필요한 console, comment, import 삭제
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.spec.ts
  packages/server/src/cafe/cafe.controller.ts
  packages/server/src/cafe/cafe.module.ts
  packages/server/src/cafe/cafe.service.spec.ts
  packages/server/src/cafe/cafe.service.ts
  packages/server/src/cafe/entities/cafeMenu.entity.ts
  packages/server/src/main.ts
  packages/server/src/middleware/logger.http.ts
  packages/server/src/order/dto/create-order.dto.ts
  packages/server/src/order/dto/orderRes.dto.ts
  packages/server/src/order/dto/ordersRes.dto.ts
  packages/server/src/order/dto/requested-order.dto.ts
  packages/server/src/order/entities/orderMenu.entity.ts
  packages/server/src/order/order.entity.spec.ts
  packages/server/src/order/order.service.spec.ts
  packages/server/src/order/order.service.ts
  packages/server/src/order/order.v2.controller.ts
  packages/server/src/order/order.v3.controller.ts
  packages/server/src/utils/dateTime.util.spec.ts
  packages/server/src/utils/getMySQLTestTypeOrmModule.ts
  packages/server/test/e2e/order/order.e2e.spec.ts
  packages/server/test/integration/order/order.int.spec.ts
Labels: 💻 백엔드, 🔨 REFACTOR

#185 디자인 마무리 작업 및 최적화 적용
  packages/client/src/Layout.tsx
  packages/client/src/Router.tsx
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/CountSelector/styled.ts
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/Footer/styled.ts
  packages/client/src/components/Header/__snapshots__/index.test.tsx.snap
  packages/client/src/components/Header/index.tsx
  packages/client/src/components/LeftArrow/index.tsx
  packages/client/src/components/LeftArrow/styled.ts
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDateList/styled.ts
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/components/OrderList/styled.ts
  packages/client/src/hooks/useOrderDates.tsx
  packages/client/src/hooks/useOrderStatus.tsx
  packages/client/src/pages/Home/index.test.tsx
  packages/client/src/pages/MyPage/index.tsx
  packages/client/src/pages/MyPage/styled.ts
  packages/client/src/pages/Signin/__snapshots__/index.spec.tsx.snap
  packages/client/src/pages/Signin/styled.ts
  packages/client/src/pages/customer/Cart/components/CartFooter/styled.ts
  packages/client/src/pages/customer/Cart/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/MenuInformation/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/OptionSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/OrderButton/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/TemperatureSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/components/TemperatureSelector/styled.ts
  packages/client/src/pages/customer/MenuList/components/MenuItem/styled.ts
  packages/client/src/pages/customer/MenuList/components/SnackBar/index.tsx
  packages/client/src/pages/customer/MenuList/components/SnackBar/styled.ts
  packages/client/src/pages/customer/MenuList/styled.ts
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/pages/customer/OrderStatus/styled.ts
  packages/client/src/pages/manager/AcceptList/index.test.tsx
Labels: 🎨 프론트엔드, ✨ FEAT, 🔨 REFACTOR

#187 FE - Week6
  packages/client/src/Layout.tsx
  packages/client/src/Router.tsx
  packages/client/src/components/Button/styled.ts
  packages/client/src/components/CountSelector/index.test.tsx
  packages/client/src/components/CountSelector/styled.ts
  packages/client/src/components/Footer/index.spec.tsx
  packages/client/src/components/Footer/index.tsx
  packages/client/src/components/Footer/styled.ts
  packages/client/src/components/Header/__snapshots__/index.test.tsx.snap
  packages/client/src/components/Header/index.test.tsx
  packages/client/src/components/Header/index.tsx
  packages/client/src/components/LeftArrow/index.tsx
  packages/client/src/components/LeftArrow/styled.ts
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDateList/styled.ts
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/components/OrderList/styled.ts
  packages/client/src/hooks/useOrderDates.tsx
  packages/client/src/hooks/useOrderStatus.tsx
  packages/client/src/mocks/data/cart.ts
  packages/client/src/mocks/data/order.ts
  packages/client/src/mocks/handlers/order.ts
  packages/client/src/pages/Home/index.test.tsx
  packages/client/src/pages/Home/index.tsx
  packages/client/src/pages/MyPage/index.spec.tsx
  packages/client/src/pages/MyPage/index.tsx
  packages/client/src/pages/MyPage/styled.ts
  packages/client/src/pages/Signin/__snapshots__/index.spec.tsx.snap
  packages/client/src/pages/Signin/index.spec.tsx
  packages/client/src/pages/Signin/styled.ts
  packages/client/src/pages/Signup/index.spec.tsx
  packages/client/src/pages/customer/Cart/components/CartFooter/styled.ts
  packages/client/src/pages/customer/Cart/components/CartItem/index.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/pages/customer/Cart/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/MenuInformation/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/OptionSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/OrderButton/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/components/TemperatureSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/components/TemperatureSelector/styled.ts
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
  packages/client/src/pages/customer/MenuList/components/MenuItem/index.tsx
  packages/client/src/pages/customer/MenuList/components/MenuItem/styled.ts
  packages/client/src/pages/customer/MenuList/components/SnackBar/index.tsx
  packages/client/src/pages/customer/MenuList/components/SnackBar/styled.ts
  packages/client/src/pages/customer/MenuList/styled.ts
  packages/client/src/pages/customer/OrderStatus/index.spec.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/pages/customer/OrderStatus/styled.ts
  packages/client/src/pages/manager/AcceptList/index.test.tsx
  packages/client/src/utils/index.ts
Labels: 🎨 프론트엔드, ✨ FEAT, 🔨 REFACTOR

#189 Hotfix 주문 내역 조회 시, size, type property 추가
  packages/server/src/order/dto/ordersRes.dto.ts
Labels: 💻 백엔드, ✨ FEAT

#190 업주 주문 내역 페이지 수정
  packages/client/src/components/OrderDateList/index.tsx
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderDetailList/styled.ts
  packages/client/src/types/index.ts
Labels: 🎨 프론트엔드, 🐞 BUG

#191 hotfix: REJECTED 주문 상태 처리
  packages/client/src/constants.ts
  packages/client/src/mocks/data/order.ts
  packages/client/src/mocks/handlers/order.ts
  packages/client/src/pages/customer/OrderStatus/index.spec.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/pages/customer/OrderStatus/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#192 Hotfix Order Stauts 조회 API, Access Token Expire 설정
  packages/server/src/auth/strategy/jwt.strategy.ts
  packages/server/src/order/dto/orderRes.dto.ts
  packages/server/src/order/order.service.ts
  packages/server/src/order/order.v1.controller.ts
Labels: 💻 백엔드, ✨ FEAT

#193 주문 상태 페이지 수정
  packages/client/src/hooks/useOrderStatus.tsx
  packages/client/src/mocks/data/order.ts
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/pages/customer/OrderStatus/styled.ts
Labels: 🎨 프론트엔드, ✨ FEAT

#194 README 작성
  README.md
Labels: 📚 DOCS

#195 mock login 구현
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/user/user.service.ts
Labels: 💻 백엔드, ✨ FEAT

#197 Hotfix/script 버그 수정
  packages/server/scripts/prod.deploy.sh
Labels: 🐞 BUG

#200 캠퍼 임시 로그인, 토스트(Toast), 일부 페이지 렌더링 수정, 불필요 코드 제거
  packages/client/src/App.tsx
  packages/client/src/Layout.tsx
  packages/client/src/Router.tsx
  packages/client/src/components/CountSelector/index.test.tsx
  packages/client/src/components/CountSelector/index.tsx
  packages/client/src/components/Header/__snapshots__/index.test.tsx.snap
  packages/client/src/components/OrderDetailList/index.tsx
  packages/client/src/components/OrderList/index.tsx
  packages/client/src/components/OrderList/styled.ts
  packages/client/src/components/Toast/index.tsx
  packages/client/src/components/Toast/styled.ts
  packages/client/src/hooks/useFetch.tsx
  packages/client/src/hooks/useOrderStatus.tsx
  packages/client/src/index.tsx
  packages/client/src/pages/MyPage/index.spec.tsx
  packages/client/src/pages/MyPage/index.tsx
  packages/client/src/pages/MyPage/styled.ts
  packages/client/src/pages/Signin/__snapshots__/index.spec.tsx.snap
  packages/client/src/pages/Signin/index.tsx
  packages/client/src/pages/Signin/styled.ts
  packages/client/src/pages/Signup/index.tsx
  packages/client/src/pages/customer/Cart/components/CartFooter/index.tsx
  packages/client/src/pages/customer/Cart/index.spec.tsx
  packages/client/src/pages/customer/MenuDetail/components/OrderButton/index.tsx
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/components/SizeSelector/index.test.tsx
  packages/client/src/pages/customer/MenuDetail/components/TemperatureSelector/__snapshots__/index.test.tsx.snap
  packages/client/src/pages/customer/MenuDetail/index.test.tsx
  packages/client/src/pages/customer/MenuList/components/MenuItem/index.tsx
  packages/client/src/pages/customer/MenuList/components/SnackBar/index.tsx
  packages/client/src/pages/customer/MenuList/index.tsx
  packages/client/src/pages/customer/OrderStatus/index.tsx
  packages/client/src/stores/index.ts
  packages/client/src/utils/localStorage.ts
  packages/client/src/utils/testSetup.tsx
Labels: 🎨 프론트엔드, 🐞 BUG, ✨ FEAT

#199 Pm2 설정
  .github/workflows/test.yml
  packages/server/Dockerfile.prod
  packages/server/package.json
  packages/server/pm2.prod.yml
Labels: 💻 백엔드, ✨ FEAT

#202 메뉴 상세 정보 조회 버그 수정
  packages/client/src/pages/customer/MenuDetail/index.tsx
Labels: 🎨 프론트엔드, 🐞 BUG

#203 hotfix BE cors origin 수정, session password 환경변수 지정
  packages/server/src/setNestApp.ts
Labels: 💻 백엔드
